# Generated by Django 4.2.7 on 2023-11-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_livro', models.CharField(max_length=70)),
                ('decricao', models.TextField()),
                ('n_paginas', models.IntegerField()),
            ],
        ),
    ]
